#!/usr/bin/env bash
# Multi-user LiteLLM gateway in front of serve-laguna.sh's llama-server.
# See README "Multi-user gateway" for the full picture.
#
#   users --(own key)--> LiteLLM :4000 --(internal key)--> llama-server 127.0.0.1:8000
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

SECRETS_FILE=".secrets/gateway.env"
CONFIG="gateway/litellm-config.yaml"
VENV=".venv-litellm"
LOG_DIR="logs"
PID_FILE="$LOG_DIR/gateway.pid"
LOG_FILE="$LOG_DIR/gateway.log"
GATEWAY_HOST="${GATEWAY_HOST:-0.0.0.0}"
GATEWAY_PORT="${GATEWAY_PORT:-4000}"
MODEL_ALIAS="local-coder"

log()  { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }
warn() { printf '[%s] WARNING: %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >&2; }
die()  { printf '[%s] ERROR: %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >&2; exit 1; }

load_secrets() {
  [[ -f "$SECRETS_FILE" ]] || die "$SECRETS_FILE not found. Run './gateway.sh init' first."
  set -a
  # shellcheck disable=SC1090
  source "$SECRETS_FILE"
  set +a
}

api() {
  # api <METHOD> <path> [json-body]
  local method="$1" path="$2" body="${3:-}"
  curl -sS -X "$method" "http://127.0.0.1:${GATEWAY_PORT}${path}" \
    -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
    -H 'Content-Type: application/json' ${body:+-d "$body"}
}

psql_q() {
  PGPASSWORD="$PG_PASSWORD" psql -h 127.0.0.1 -U litellm -d litellm -v ON_ERROR_STOP=1 "$@"
}

cmd_init() {
  [[ -x "$VENV/bin/litellm" ]] || {
    log "Installing LiteLLM into $VENV (gitignored)..."
    python3 -m venv "$VENV"
    "$VENV/bin/pip" install --quiet --upgrade pip
    "$VENV/bin/pip" install --quiet "litellm[proxy]"
  }
  # litellm[proxy] (1.104) no longer pulls in the Prisma client it needs for
  # the key/usage database — confirmed by hand: without this, `serve` dies
  # with "No module named 'prisma'". Generate it from LiteLLM's own schema.
  if ! "$VENV/bin/python" -c 'import prisma; prisma.Prisma' >/dev/null 2>&1; then
    log "Installing + generating the Prisma client for LiteLLM..."
    "$VENV/bin/pip" install --quiet prisma
    local schema
    schema="$(find "$VENV/lib" -path '*litellm/proxy/schema.prisma' | head -1)"
    [[ -n "$schema" ]] || die "LiteLLM's schema.prisma not found under $VENV."
    PATH="$SCRIPT_DIR/$VENV/bin:$PATH" "$VENV/bin/prisma" generate --schema "$schema" >/dev/null
  fi
  if [[ -f "$SECRETS_FILE" ]]; then
    log "$SECRETS_FILE already exists — keeping it (rotating LITELLM_SALT_KEY would make stored data unreadable)."
  else
    [[ -f .secrets/api_key ]] || die ".secrets/api_key not found. Run './serve-laguna.sh init' first."
    mkdir -p .secrets && chmod 700 .secrets
    local pg_pw; pg_pw="$(openssl rand -hex 24)"
    umask 077
    cat > "$SECRETS_FILE" <<EOF
# Generated by gateway.sh init. Never commit this file.
# LITELLM_MASTER_KEY: admin key — creates/revokes user keys. Don't hand it out.
LITELLM_MASTER_KEY=sk-$(openssl rand -hex 24)
# LITELLM_SALT_KEY: encrypts data LiteLLM stores. Never change it once set.
LITELLM_SALT_KEY=sk-$(openssl rand -hex 24)
PG_PASSWORD=${pg_pw}
DATABASE_URL=postgresql://litellm:${pg_pw}@127.0.0.1:5432/litellm
# Key LiteLLM uses to reach llama-server (= .secrets/api_key).
UPSTREAM_API_KEY=$(cat .secrets/api_key)
EOF
    log "Wrote $SECRETS_FILE."
  fi
  log "Next: run the one-time root setup (Postgres, firewall, boot persistence):"
  log "  sudo ./gateway/setup-root.sh"
}

cmd_serve() {
  load_secrets
  [[ -x "$VENV/bin/litellm" ]] || die "LiteLLM not installed. Run './gateway.sh init'."
  if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    die "Gateway already running (PID $(cat "$PID_FILE"))."
  fi
  curl -sf http://127.0.0.1:8000/health >/dev/null 2>&1 \
    || warn "llama-server isn't answering on 127.0.0.1:8000 yet — the gateway will start, but requests fail until it is ('./serve-laguna.sh serve')."
  mkdir -p "$LOG_DIR"
  log "Starting LiteLLM on ${GATEWAY_HOST}:${GATEWAY_PORT}..."
  # LiteLLM shells out to the `prisma` CLI (in the venv) to create/migrate
  # its tables on startup.
  export PATH="$SCRIPT_DIR/$VENV/bin:$PATH"
  setsid "$VENV/bin/litellm" --config "$CONFIG" --host "$GATEWAY_HOST" --port "$GATEWAY_PORT" \
    >> "$LOG_FILE" 2>&1 < /dev/null &
  echo $! > "$PID_FILE"
  local tries=90
  until curl -sf "http://127.0.0.1:${GATEWAY_PORT}/health/liveliness" >/dev/null 2>&1; do
    tries=$((tries - 1))
    [[ "$tries" -gt 0 ]] || die "Gateway didn't come up within 3 min. See $LOG_FILE."
    kill -0 "$(cat "$PID_FILE")" 2>/dev/null || die "Gateway exited during startup. See $LOG_FILE."
    sleep 2
  done
  log "Gateway up: http://$(hostname -I | awk '{print $1}'):${GATEWAY_PORT}/v1  (model: ${MODEL_ALIAS})"
}

cmd_stop() {
  [[ -f "$PID_FILE" ]] || { log "Gateway not running (no PID file)."; return 0; }
  local pid; pid="$(cat "$PID_FILE")"
  if kill -0 "$pid" 2>/dev/null; then
    kill -TERM "$pid"
    for _ in $(seq 1 15); do kill -0 "$pid" 2>/dev/null || break; sleep 1; done
    kill -0 "$pid" 2>/dev/null && kill -KILL "$pid"
  fi
  rm -f "$PID_FILE"
  log "Gateway stopped."
}

cmd_status() {
  if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    log "Gateway running (PID $(cat "$PID_FILE"))."
  else
    log "Gateway not running."
  fi
  curl -sf "http://127.0.0.1:${GATEWAY_PORT}/health/liveliness" >/dev/null 2>&1 && log "gateway /health/liveliness: OK" || warn "gateway not answering on :${GATEWAY_PORT}"
  curl -sf http://127.0.0.1:8000/health >/dev/null 2>&1 && log "llama-server :8000: OK" || warn "llama-server not answering on :8000"
}

cmd_add_user() {
  # add-user <name> [--tpm N] [--rpm N] [--budget USD] [--parallel N]
  load_secrets
  local name="${1:-}"; shift || true
  [[ -n "$name" ]] || die "Usage: ./gateway.sh add-user <name> [--tpm N] [--rpm N] [--budget USD] [--parallel N]"
  # max_parallel_requests=3 by default. Was 1, but real clients send
  # several requests at once — confirmed 2026-10-06: a user's IDE client
  # fired a background request alongside the main one and got 429 "Rate
  # limit exceeded ... max_parallel_requests" with the server idle. Extra
  # requests beyond the 2 llama-server slots just queue there. Trade-off:
  # one busy user can hold both slots; lower with set-limits if that bites.
  local tpm="null" rpm="null" budget="null" parallel=3
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tpm) tpm="$2"; shift 2 ;;
      --rpm) rpm="$2"; shift 2 ;;
      --budget) budget="$2"; shift 2 ;;
      --parallel) parallel="$2"; shift 2 ;;
      *) die "Unknown option: $1" ;;
    esac
  done
  local body resp key
  body="$(jq -n --arg a "$name" --arg m "$MODEL_ALIAS" --argjson tpm "$tpm" --argjson rpm "$rpm" \
    --argjson budget "$budget" --argjson par "$parallel" \
    '{key_alias:$a, models:[$m], max_parallel_requests:$par, tpm_limit:$tpm, rpm_limit:$rpm, max_budget:$budget, metadata:{user:$a}}
     | with_entries(select(.value != null))')"
  resp="$(api POST /key/generate "$body")"
  key="$(jq -r '.key // empty' <<<"$resp")"
  [[ -n "$key" ]] || die "Key creation failed: $resp"
  cat <<EOF

User '${name}' created. Give them these three things — the key is shown only once:

  Base URL:  http://$(hostname -I | awk '{print $1}'):${GATEWAY_PORT}/v1
  API key:   ${key}
  Model:     ${MODEL_ALIAS}

qwen-code users, from a clone of this repo:
  SERVER_HOST=$(hostname -I | awk '{print $1}') CLIENT_PORT=${GATEWAY_PORT} CLIENT_API_KEY=${key} \\
    CLIENT_MODEL_NAME=${MODEL_ALIAS} ./serve-laguna.sh wire-qwen-code

EOF
}

cmd_set_limits() {
  # set-limits <name> [--parallel N] [--tpm N] [--rpm N] [--budget USD]
  # Use "none" to clear a limit, e.g. --tpm none.
  load_secrets
  local name="${1:-}"; shift || true
  [[ -n "$name" && $# -gt 0 ]] || die "Usage: ./gateway.sh set-limits <name> [--parallel N] [--tpm N] [--rpm N] [--budget USD]  (use 'none' to clear)"
  local token
  token="$(psql_q -At -c "SELECT token FROM \"LiteLLM_VerificationToken\" WHERE key_alias = '${name//\'/}'")"
  [[ -n "$token" ]] || die "No gateway user '$name'."
  local updates='{}' field val
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --parallel) field=max_parallel_requests ;;
      --tpm) field=tpm_limit ;;
      --rpm) field=rpm_limit ;;
      --budget) field=max_budget ;;
      *) die "Unknown option: $1" ;;
    esac
    val="$2"; [[ "$val" == none ]] && val=null
    updates="$(jq --arg f "$field" --argjson v "$val" '.[$f] = $v' <<<"$updates")"
    shift 2
  done
  api POST /key/update "$(jq --arg k "$token" '. + {key: $k}' <<<"$updates")" | jq -c '{key_alias, max_parallel_requests, tpm_limit, rpm_limit, max_budget}'
}

cmd_list_users() {
  load_secrets
  psql_q -c "SELECT key_alias AS name, key_name AS key_hint, max_parallel_requests AS par, tpm_limit, rpm_limit,
                    max_budget, round(spend::numeric, 4) AS spend, blocked, created_at::date AS created
             FROM \"LiteLLM_VerificationToken\" ORDER BY created_at;"
}

cmd_revoke_user() {
  load_secrets
  local name="${1:-}"; [[ -n "$name" ]] || die "Usage: ./gateway.sh revoke-user <name>"
  api POST /key/delete "$(jq -n --arg a "$name" '{key_aliases:[$a]}')"; echo
}

cmd_usage() {
  # usage [days] — per-user token totals over the last N days (default 30).
  # LiteLLM writes spend logs in batches (~every 60s), so the last minute
  # of requests may not show yet. Times are shown in this box's timezone
  # (LiteLLM stores UTC).
  load_secrets
  local days="${1:-30}"
  psql_q -c "SELECT CASE WHEN v.key_alias IS NOT NULL THEN v.key_alias
                         WHEN s.metadata->>'user_api_key_alias' IS NOT NULL THEN (s.metadata->>'user_api_key_alias') || ' (revoked)'
                         ELSE '(admin/master key)' END AS name, count(*) AS requests,
                    sum(s.prompt_tokens) AS prompt_tokens, sum(s.completion_tokens) AS completion_tokens,
                    sum(s.total_tokens) AS total_tokens, max(s.\"startTime\" AT TIME ZONE 'UTC')::timestamptz(0) AS last_used
             FROM \"LiteLLM_SpendLogs\" s
             LEFT JOIN \"LiteLLM_VerificationToken\" v ON v.token = s.api_key
             WHERE s.\"startTime\" > (now() AT TIME ZONE 'UTC') - interval '${days} days'
             GROUP BY 1 ORDER BY total_tokens DESC NULLS LAST;"
}

cmd_install_services() {
  # install-services [env-file] — systemd --user units so llama-server and
  # the gateway start at boot (needs linger: sudo ./gateway/setup-root.sh).
  # Restart is left to the existing selftest-gated watchdog
  # (./serve-laguna.sh install-watchdog), not systemd, so the two don't fight
  # over restarting llama-server.
  local env_file="${1:-laguna.env}"
  [[ -f "$env_file" ]] || die "$env_file not found."
  local unit_dir="$HOME/.config/systemd/user"
  mkdir -p "$unit_dir"
  cat > "$unit_dir/llm-server.service" <<EOF
[Unit]
Description=llama-server (${env_file}) for the LiteLLM gateway

[Service]
Type=forking
WorkingDirectory=${SCRIPT_DIR}
Environment=ENV_FILE=${env_file}
ExecStart=${SCRIPT_DIR}/serve-laguna.sh serve
ExecStop=${SCRIPT_DIR}/serve-laguna.sh stop
PIDFile=${SCRIPT_DIR}/logs/laguna.pid
TimeoutStartSec=600

[Install]
WantedBy=default.target
EOF
  cat > "$unit_dir/llm-gateway.service" <<EOF
[Unit]
Description=LiteLLM multi-user gateway (port ${GATEWAY_PORT})
After=llm-server.service
Wants=llm-server.service

[Service]
Type=forking
WorkingDirectory=${SCRIPT_DIR}
# Postgres is a system service; wait for it rather than racing it at boot.
ExecStartPre=/bin/bash -c 'for i in \$(seq 1 60); do pg_isready -q -h 127.0.0.1 && exit 0; sleep 2; done; exit 1'
ExecStart=${SCRIPT_DIR}/gateway.sh serve
ExecStop=${SCRIPT_DIR}/gateway.sh stop
PIDFile=${SCRIPT_DIR}/logs/gateway.pid
TimeoutStartSec=300

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable llm-server.service llm-gateway.service
  log "Installed + enabled llm-server.service (ENV_FILE=${env_file}) and llm-gateway.service."
  log "They start at next boot. To hand over the currently running processes to systemd now:"
  log "  ./gateway.sh stop; ./serve-laguna.sh stop; systemctl --user start llm-gateway.service"
  loginctl show-user "$USER" -p Linger 2>/dev/null | grep -q yes \
    || warn "Linger is off — these won't start until you log in. Run: sudo ./gateway/setup-root.sh"
}

usage() {
  cat <<'EOF'
Usage: ./gateway.sh <command>

  init                     Install LiteLLM, generate .secrets/gateway.env
  serve | stop | status    Run/stop/check the gateway (port 4000)
  add-user <name> [--tpm N] [--rpm N] [--budget USD] [--parallel N]
                           Create a user key (printed once). Default: 3 requests at a time
  list-users               Keys, limits and spend
  set-limits <name> [--parallel N] [--tpm N] [--rpm N] [--budget USD]
                           Change a user's limits in place ('none' clears one)
  revoke-user <name>       Delete a user's key immediately
  usage [days]             Per-user token totals (default: last 30 days)
  install-services [env]   Start llama-server + gateway at boot (default env: laguna.env)

One-time root setup (Postgres, firewall, start at boot): sudo ./gateway/setup-root.sh
EOF
}

case "${1:-}" in
  init) cmd_init ;;
  serve) cmd_serve ;;
  stop) cmd_stop ;;
  status) cmd_status ;;
  add-user) shift; cmd_add_user "$@" ;;
  list-users) cmd_list_users ;;
  set-limits) shift; cmd_set_limits "$@" ;;
  revoke-user) shift; cmd_revoke_user "$@" ;;
  usage) shift; cmd_usage "$@" ;;
  install-services) shift; cmd_install_services "$@" ;;
  *) usage; exit 1 ;;
esac
